### ISSUE TITLE
DialogParser?

### ISSUE THREAD

**Issue by shaneboulden** [ramrexx/CloudForms_Essentials#1]
This is an amazing resource for managing OpenStack from ManageIQ/ Cloudforms! Thanks very much for publishing to Github.

A quick question - the build_vm_provision_request.rb method under the Service provisioning state machine references a DialogParser method. I couldn't find the method in its referenced location (/Service/Provisioning/StateMachines/Methods/DialogParser). Can anyone please help out?

Thanks again.

Shane

**Comment by stencell** [comment]
Shane,
Check out the ManageIQ domain that ships with the product. The DialogParser method was not modified, so it is not included with CloudForms_Essentials. When a method is called, it will work its way through each of the automate domains in their priority order until it finds the first instance of that method to run.

**Comment by shaneboulden** [comment]
Ah, awesome. Thanks Nate!
