### ISSUE TITLE
The Automate datastore is missing ec2 methods

### ISSUE THREAD

**Issue by PUPPBJS** [ramrexx/CloudForms_Essentials#15]
The latest versions is missing the Methods from Integration\Amazon\EC2 and Integration\Amazon\RDS

Which causes this error on setting up an EC2 instance

[----] I, [2016-10-28T10:27:32.060148 #3264:699998]  INFO -- : Q-task_id([miq_provision_1000000000105]) Processing State=[PostProvision2]
[----] I, [2016-10-28T10:27:32.060457 #3264:699998]  INFO -- : Q-task_id([miq_provision_1000000000105]) Following Relationship [miqaedb:/Integration/Amazon/EC2/Methods/EC2_Synchronize_Tags#create]
[----] E, [2016-10-28T10:27:32.185635 #3264:699998] ERROR -- : Q-task_id([miq_provision_1000000000105]) Class [Integration/Amazon/EC2/Methods] not found in MiqAeDatastore
[----] I, [2016-10-28T10:27:32.185787 #3264:699998]  INFO -- : Q-task_id([miq_provision_1000000000105]) Followed  Relationship [miqaedb:/Integration/Amazon/EC2/Methods/EC2_Synchronize_Tags#create]
[----] E, [2016-10-28T10:27:32.185949 #3264:699998] ERROR -- : Q-task_id([miq_provision_1000000000105]) State=<PostProvision2> running  raised exception: <empty relationship>
[----] W, [2016-10-28T10:27:32.186156 #3264:699998]  WARN -- : Q-task_id([miq_provision_1000000000105]) Error in State=[PostProvision2]
[----] I, [2016-10-28T10:27:32.186346 #3264:699998]  INFO -- : Q-task_id([miq_provision_1000000000105]) In State=[PostProvision2], invoking [on_error] method=[update_provision_status(status => 'Error Applying PostProvision1 Customizations')]

I copied the Methods from a previous version and all worked ok.

**Comment by ramrexx** [comment]
You should not have to copy the methods back in. I moved them to the statemachines class. I have just corrected to repo so that they are pointed to the correct class. 

Thanks for pointing this one out.
