### ISSUE TITLE
Error in RHEV - Build a VM * catalog items

### ISSUE THREAD

**Issue by sgenchev** [ramrexx/CloudForms_Essentials#3]
When requesting a VM from oVirt I get an error instead of list of available vm templates.  evm.log has:

`[----] E, [2016-04-22T09:00:45.990981 #3202:fdf034] ERROR -- : <AutomationEngine> Method STDERR: (druby://127.0.0.1:32809) /var/www/miq/vmdb/lib/miq_automation_engine/engine/miq_ae_service_model_base.rb:179:in method_missing: undefined method miq_templates for #<MiqAeMethodService::MiqAeServiceManageIQ_Providers_Redhat_InfraManager:0x0000000357b608> (NoMethodError)
[----] E, [2016-04-22T09:00:45.991696 #3202:fdf034] ERROR -- : <AutomationEngine> Method STDERR:    from <code: provider.miq_templates.each do |template|>:115:in <main> provider.miq_templates.each do |template|`

If I go to  Integration/RedHat/RHEV/DynamicDialogs/list_rhev_template_guids,  and comment out  searching for templates on a provider (lines 114-120), I can get a list of all oVirt templates.

So, to me it looks like I do get a provider object, but it is missing miq_templates method. Should this work with  ManageIQ/oVirt, or does it require Cloudforms/RHEV?
I have ManageIQ Capablanca and oVirt 3.6

**Comment by stencell** [comment]
Honestly, we did not test this with the upstream versions of either product. I have no reason to believe they shouldn't work, but we just haven't had time to look at it yet.

If you go into a rails console and run something like the following...what do you get back?

Enter rails console and enter MIQ workspace (make sure you have sourced cloudforms_essentialsrc for alias). After entering the console, past the $evm=xxx line that is echo'd:

`railsc`

Set your provider and see what methods are available:

`provider = $evm.vmdb(:ManageIQ_Providers_InfraManager).all.detect { |x| x.name == "<your-provider-name>" }`
`provider.methods`

I've tested this against both RHEV 3.5 & 3.6 and I am able to pull back the templates with each.

You can also add a line of code just after 112 to log in automation.log what the provider object is so you know what it is picking up before it fails and exits.

`log(:info, "Provider found: #{provider.inspect}")`

**Comment by ramrexx** [comment]
@sgenchev - Were you able to get past this issue?

**Comment by sgenchev** [comment]
I am sorry, was out of the whole computer business. 
Log line for provider below:
There is no mid_templates method. Closest one is total_miq_templates. Where does this method come from? oVirt SDK, Miq?

 Thanks!

```
  Provider found: #<MiqAeServiceManageIQ_Providers_Redhat_InfraManager:0x897f678 
@object=#<ManageIQ::Providers::Redhat::InfraManager id: 2, name: "oVirt-prod", port: "443",
hostname: "olaxpa-ovirtm01.garmin.com", ipaddress: nil, created_on: "2016-02-02 19:39:01", 
updated_on: "2016-05-05 13:13:57", guid: "9bf6565e-c9e4-11e5-8ac2-001a4a160158", zone_id: 1, 
type: "ManageIQ::Providers::Redhat::InfraManager", api_version: "3.6.4.1", uid_ems: nil, 
host_default_vnc_port_start: nil, host_default_vnc_port_end: nil, provider_region: nil, 
last_refresh_error: nil, last_refresh_date: "2016-05-05 13:13:57", provider_id: nil, security_protocol: 
nil, realm: nil, tenant_id: 1>, @virtual_columns=["aggregate_cpu_speed", 
"aggregate_cpu_total_cores", "aggregate_disk_capacity", "aggregate_logical_cpus", 
"aggregate_memory", "aggregate_physical_cpus", "aggregate_vm_cpus", "aggregate_vm_memory", 
"authentication_status", "cpu_usagemhz_rate_average_avg_over_time_period", 
"cpu_usagemhz_rate_average_high_over_time_period", 
"cpu_usagemhz_rate_average_low_over_time_period", 
"derived_memory_used_avg_over_time_period", "derived_memory_used_high_over_time_period", 
"derived_memory_used_low_over_time_period", "emstype", "emstype_description", 
"last_refresh_status", "max_cpu_usage_rate_average_avg_over_time_period", 
"max_cpu_usage_rate_average_avg_over_time_period_without_overhead", 
"max_cpu_usage_rate_average_high_over_time_period", 
"max_cpu_usage_rate_average_high_over_time_period_without_overhead", 
"max_cpu_usage_rate_average_low_over_time_period", 
"max_cpu_usage_rate_average_low_over_time_period_without_overhead", 
"max_mem_usage_absolute_average_avg_over_time_period", 
"max_mem_usage_absolute_average_avg_over_time_period_without_overhead", 
"max_mem_usage_absolute_average_high_over_time_period", 
"max_mem_usage_absolute_average_high_over_time_period_without_overhead", 
"max_mem_usage_absolute_average_low_over_time_period", 
"max_mem_usage_absolute_average_low_over_time_period_without_overhead", 
"region_description", "region_number", "total_clusters", "total_hosts", "total_miq_templates", 
"total_storages", "total_vms", "total_vms_and_templates", "total_vms_never", "total_vms_off", 
"total_vms_on", "total_vms_suspended", "total_vms_unknown", "zone_name"], @associations=
["ems_clusters", "ems_events", "ems_folders", "hosts", "provider", "resource_pools", "storages", 
"tenant", "vms"]>
```

**Comment by ramrexx** [comment]
So here are my associations for my provider:

@associations=["customization_specs", "ems_clusters", "ems_events", "ems_folders", "hosts", "miq_templates", "provider", "resource_pools", "storages", "tenant", "vms"]

I am wondering if something got missed in the upstream ManageIQ project?  Again, CloudForms_Essentials was built for the downstream stable version.

I would highly recommend that you submit this question to talk.manageiq.org because this method should be there. Closing this issue.
