### ISSUE TITLE
Installation without internet access

### ISSUE THREAD

**Issue by soniah** [ramrexx/CloudForms_Essentials#30]
As a system administrator, on a CF appliance that doesn't have internet access, I would like to install this project.

For example by downloading a .tgz/.zip to my laptop, then uploading via a vpn, then running Ansible.

**Comment by ramrexx** [comment]
Thank you for the suggestion. I have modified the README as well as the installation playbook to accept offline installs.

**Comment by soniah** [comment]
Thank you.
