### ISSUE TITLE
Cannot Import the automation code

### ISSUE THREAD

**Issue by ProxyManagedServices** [ramrexx/CloudForms_Essentials#32]
When running the ansible playbook the automation code is not imported.
Trying to install with miqimport I got the following error:
miqimport --overwrite domain CloudForms_Essentials  /root/CloudForms_Essentials/automate
DOMAIN_OPTIONS=overwrite=true;enabled=true;
/var/www/miq/vmdb ~/CloudForms_Essentials/automate
rake aborted!
MiqAeException::FieldNotFound: Field [execute] not found in MiqAeDatastore

Than zipped the automation directory, and try to import with the MIQ/CF webui the following error is raised:
Field [execute] not found in MiqAeDatastore [miq_ae_tools/import_automate_datastore]

Tried this in MIQ Fine-3 and CF 4.5

**Comment by ramrexx** [comment]
Looks like there was an error in the instance variable. I have corrected the issue. Please try again.

**Comment by ProxyManagedServices** [comment]
Thanks Kevin,
It is working.
