### ISSUE TITLE
Import deletes existing content

### ISSUE THREAD

**Issue by kuklis** [ramrexx/CloudForms_Essentials#33]
I had a button defined in (an existing) button group Service/Service Ops. The (offline) import method deleted this button. Import should check existing content conflicts.

**Comment by kuklis** [comment]
The button seems to be still in the DB: I tried to re-add it but received the following error message:

> Name has already been taken

**Comment by ramrexx** [comment]
Yes that is a challenge when using the consulting import/export scripts.
