### ISSUE TITLE
Setup Approval Policy for Service Request

### ISSUE THREAD

**Issue by coolpalani** [ramrexx/CloudForms_Essentials#34]
Do you have something like this which you had already done.

https://pemcg.gitbooks.io/introduction-to-cloudforms-automation/content/chapter15/approval.html

When any service request raised by end user, it should be approved by administrator.

**Comment by ramrexx** [comment]
I haven't done anything with this in a while now but you should be able to just toggle the service auto approval state machine:

https://pemcg.gitbooks.io/introduction-to-cloudforms-automation/content/chapter17/approval_and_quota.html
