### ISSUE TITLE
When I try to import roles or service catalogs in CF4.1 it fails in the rake script

### ISSUE THREAD

**Issue by vestival** [ramrexx/CloudForms_Essentials#4]
Hello,

When I try to import roles or service catalogs in CF4.1 Beta 5 (5.6.0.10-rc2.1) it fails

[root@cloudforms CloudForms_Essentials-master]# /usr/bin/miqimport service_catalogs /root/CloudForms_Essentials-master/service_catalogs/ --trace
/var/www/miq/vmdb ~/CloudForms_Essentials-master
DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `config.public_file_server.enabled = false` instead.
 (called from serve_static_files= at /opt/rh/cfme-gemset/gems/railties-5.0.0.rc1/lib/rails/application/configuration.rb:80)
Service Catalog: [Cloud Services]
rake aborted!
NoMethodError: undefined method `find_or_create_by_name' for #<ServiceTemplateCatalog::ActiveRecord_Relation:0x0000000cd0a4d8>
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/relation/delegation.rb:123:in`method_missing'
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/relation/delegation.rb:93:in `method_missing'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:53:in`block in import_service_template_catalogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:51:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:51:in`import_service_template_catalogs'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:12:in `block (3 levels) in import'
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`block in transaction'
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in`transaction'
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/transactions.rb:211:in `transaction'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:11:in`block (2 levels) in import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:8:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:8:in`block in import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:5:in `foreach'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:5:in`import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:279:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:service_catalogs:import
(See full trace by running task with --trace)
~/CloudForms_Essentials-master
[root@cloudforms CloudForms_Essentials-master]# /usr/bin/miqimport roles /root/CloudForms_Essentials-master/roles/roles.yml 
/var/www/miq/vmdb ~/CloudForms_Essentials-master
DEPRECATION WARNING:`config.serve_static_files`is deprecated and will be removed in Rails 5.1.
Please use`config.public_file_server.enabled = false`instead.
 (called from serve_static_files= at /opt/rh/cfme-gemset/gems/railties-5.0.0.rc1/lib/rails/application/configuration.rb:80)
rake aborted!
RoleImportExport::ParsedNonDialogYamlError: RoleImportExport::ParsedNonDialogYamlError
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:57:in`rescue in import_roles'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:48:in `import_roles'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:8:in`import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:85:in `block (3 levels) in <top (required)>'
NoMethodError: undefined method`find_or_create_by_name' for #Class:0x000000026475d8
/opt/rh/cfme-gemset/bundler/gems/rails-61b074f40164/activerecord/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:53:in`block in import_roles'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:49:in `each'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:49:in`import_roles'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:8:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_roles.rake:85:in`block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:roles:import
(See full trace by running task with --trace)

**Comment by ramrexx** [comment]
We are seeing the same thing. Please open this issue with the rhconsulting repo team.

**Comment by vestival** [comment]
Sure, I did it! Thanks

https://github.com/rhtconsulting/cfme-rhconsulting-scripts/issues/56
