### ISSUE TITLE
openstack_create_loadbalancer Error

### ISSUE THREAD

**Issue by AnyISalIn** [ramrexx/CloudForms_Essentials#5]
I'm sorry you had to suffer from my foolishness.

I use this repository openstack_create_loadbalancer script, In ManageIQ Automation, syntax check is error. Even if I delete the code to make it run, there are many variables that are not defined. 

I have created the relevant dialog box, you did not finish ? or am I doing wrong? Please advise

**Comment by ramrexx** [comment]
I just updated the code today to support the new fog-openstack gem being used in 5.6. Please retry using the new updated method
