### ISSUE TITLE
build_vm_provision_request fails when missing a tennant

### ISSUE THREAD

**Issue by jeffwarnica** [ramrexx/CloudForms_Essentials#9]
Around line 367. This fails if line 255 doesn't get a valid @tenant, which is acceptable.

**Comment by ramrexx** [comment]
Jeff,
Were you able to get passed this issue? If so please share your code so that i may review.

**Comment by jeffwarnica** [comment]
Not handy. But a
`cloud_network = nil` 
or such, before the `if merged_options_hash[:cloud_network].blank?` should do it.
`

**Comment by ramrexx** [comment]
Thanks for catching this one. I have added some checks to make sure there is a tenant.
